#!/usr/bin/env python3
"""
repro_strategies.py — Java reproducer templates and execution functions.

Four strategies:
  programmatic_same_class  — reflection-based; polluter + victim on same instance
  programmatic_diff_class  — reflection-based; separate class instances
  plus_syntax              — Surefire PLUS_SYNTAX + reversealphabetical ordering
  custom_undertow          — @RunWith(DefaultServer.class) with explicit calls

Each run_* function:
  - Writes a generated Java file (if needed) to the repo's test source tree
  - Compiles and runs it via Maven
  - Cleans up the generated file unconditionally
  - Returns (exit_code, output_string)

NOT GENERALIZABLE:
  custom_undertow is hardcoded to undertow's AnnotatedEndpointTest OD pair.
  plus_syntax assumes polluter class names sort after victim class names
  alphabetically (true for the current spring-boot dataset; verify for new pairs).
"""

import os
import re
import signal
import subprocess
import textwrap
import time

from config import SKIP_FLAGS, offline_flag_for, PHASE_B_COMPILE_TIMEOUT, test_source_root_for, surefire_pre_phase_for


# ── Shared runner ──────────────────────────────────────────────────────────────

def run_cmd(cmd, cwd, env, timeout, log_path):
    """Run a shell command, write combined stdout+stderr to log_path.
    Returns (exit_code, output_string).

    Output is written directly to a file (not piped through Python) so that
    a hanging surefire forked JVM cannot block on pipe EOF.  The function
    polls the log file for test-completion markers ("Tests run:", "BUILD
    SUCCESS", "BUILD FAILURE").  Once tests have finished but the process is
    still alive (e.g. lingering Jetty threads), the entire process group is
    killed after a short grace period.  This avoids waiting for the full
    timeout on repos like http-request.
    """
    os.makedirs(os.path.dirname(log_path), exist_ok=True)

    # Completion markers that indicate Maven/surefire finished its work.
    _DONE_MARKERS = ("Tests run:", "BUILD SUCCESS", "BUILD FAILURE",
                     "No tests were run", "No tests matching")
    _GRACE_SEC = 5  # seconds to wait after tests complete before killing

    try:
        log_f = open(log_path, "w", encoding="utf-8")
        proc = subprocess.Popen(
            cmd, shell=True, stdout=log_f, stderr=subprocess.STDOUT,
            cwd=cwd, env=env,
            start_new_session=True,
        )
        log_f.close()  # child owns its own fd via dup2

        deadline = time.time() + timeout
        done_detected_at = None
        rc = None

        while time.time() < deadline:
            rc = proc.poll()
            if rc is not None:
                break  # process exited normally

            # Check log for completion markers
            try:
                with open(log_path, "r", encoding="utf-8") as f:
                    content = f.read()
                if any(m in content for m in _DONE_MARKERS):
                    if done_detected_at is None:
                        done_detected_at = time.time()
                    elif time.time() - done_detected_at >= _GRACE_SEC:
                        # Tests finished but process still alive — kill group
                        try:
                            os.killpg(proc.pid, signal.SIGKILL)
                        except (ProcessLookupError, OSError):
                            proc.kill()
                        proc.wait()
                        break
            except (FileNotFoundError, IOError):
                pass

            time.sleep(1)
        else:
            # Full timeout expired
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except (ProcessLookupError, OSError):
                proc.kill()
            proc.wait()
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(f"\nTIMEOUT after {timeout}s\n")

        rc = proc.returncode if proc.returncode is not None else 1
    except Exception as exc:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(f"ERROR launching command: {exc}\n")
        return 1, f"ERROR launching command: {exc}\n"

    with open(log_path, "r", encoding="utf-8") as f:
        output = f.read()
    return rc, output


def _cleanup(path):
    try:
        os.remove(path)
    except OSError:
        pass


# ── Template: same-class programmatic reproducer ───────────────────────────────

_SAME_CLASS_TEMPLATE = textwrap.dedent("""\
package flakyrepro;

import org.junit.Test;
import java.lang.reflect.*;
import java.util.*;

/** Generated by failure_data_collection/repro_strategies.py — deleted after run. */
public class ProgrammaticReproducer_{SAFE_KEY} {{

    @SuppressWarnings("unchecked")
    private static <A extends java.lang.annotation.Annotation>
    List<Method> getAnnotated(Class<?> cls, Class<A> ann) {{
        List<Method> result = new ArrayList<Method>();
        for (Class<?> c = cls; c != null && c != Object.class; c = c.getSuperclass()) {{
            for (Method m : c.getDeclaredMethods()) {{
                if (m.isAnnotationPresent(ann)) {{
                    m.setAccessible(true);
                    result.add(m);
                }}
            }}
        }}
        return result;
    }}

    @Test
    public void reproduce() throws Exception {{
        Class<?> cls = Class.forName("{VICTIM_CLASS}");
        Object inst = cls.getDeclaredConstructor().newInstance();

        // @BeforeClass
        for (Method m : getAnnotated(cls, org.junit.BeforeClass.class)) m.invoke(null);

        // --- POLLUTER ---
        for (Method m : getAnnotated(cls, org.junit.Before.class))  m.invoke(inst);
        try {{
            cls.getMethod("{POLLUTER_METHOD}").invoke(inst);
        }} catch (java.lang.reflect.InvocationTargetException __) {{
            // Swallow: polluter may carry @Test(expected=...) — the pollution
            // side-effect has already occurred before the exception is thrown.
        }} finally {{
            for (Method m : getAnnotated(cls, org.junit.After.class)) m.invoke(inst);
        }}

        // --- VICTIM ---
        for (Method m : getAnnotated(cls, org.junit.Before.class))  m.invoke(inst);
        try {{
            cls.getMethod("{VICTIM_METHOD}").invoke(inst);
        }} catch (java.lang.reflect.InvocationTargetException e) {{
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            System.out.println("[REPRODUCED] {SAFE_KEY}: "
                + cause.getClass().getSimpleName() + ": " + cause.getMessage());
            if (cause instanceof AssertionError) throw (AssertionError) cause;
            if (cause instanceof RuntimeException) throw (RuntimeException) cause;
            throw new AssertionError("[REPRODUCED] " + cause.getMessage(), cause);
        }} finally {{
            for (Method m : getAnnotated(cls, org.junit.After.class))      m.invoke(inst);
            for (Method m : getAnnotated(cls, org.junit.AfterClass.class)) m.invoke(null);
        }}
    }}
}}
""")


# ── Template: different-class programmatic reproducer ──────────────────────────

_DIFF_CLASS_TEMPLATE = textwrap.dedent("""\
package flakyrepro;

import org.junit.Test;
import java.lang.reflect.*;
import java.util.*;

/** Generated by failure_data_collection/repro_strategies.py — deleted after run. */
public class DiffClassReproducer_{SAFE_KEY} {{

    @SuppressWarnings("unchecked")
    private static <A extends java.lang.annotation.Annotation>
    List<Method> getAnnotated(Class<?> cls, Class<A> ann) {{
        List<Method> result = new ArrayList<Method>();
        for (Class<?> c = cls; c != null && c != Object.class; c = c.getSuperclass()) {{
            for (Method m : c.getDeclaredMethods()) {{
                if (m.isAnnotationPresent(ann)) {{
                    m.setAccessible(true);
                    result.add(m);
                }}
            }}
        }}
        return result;
    }}

    @Test
    public void reproduce() throws Exception {{
        // ── POLLUTER CLASS ────────────────────────────────────────────────
        Class<?> polCls  = Class.forName("{POLLUTER_CLASS}");
        Object   polInst = polCls.getDeclaredConstructor().newInstance();
        for (Method m : getAnnotated(polCls, org.junit.BeforeClass.class)) m.invoke(null);
        for (Method m : getAnnotated(polCls, org.junit.Before.class))      m.invoke(polInst);
        polCls.getMethod("{POLLUTER_METHOD}").invoke(polInst);
        for (Method m : getAnnotated(polCls, org.junit.After.class))       m.invoke(polInst);
        for (Method m : getAnnotated(polCls, org.junit.AfterClass.class))  m.invoke(null);

        // ── VICTIM CLASS ──────────────────────────────────────────────────
        // Wrap the entire victim lifecycle — pollution may prevent even
        // constructor or @BeforeClass from succeeding.
        Class<?> vicCls = Class.forName("{VICTIM_CLASS}");
        try {{
            Object vicInst = vicCls.getDeclaredConstructor().newInstance();
            for (Method m : getAnnotated(vicCls, org.junit.BeforeClass.class)) m.invoke(null);
            for (Method m : getAnnotated(vicCls, org.junit.Before.class))      m.invoke(vicInst);
            try {{
                vicCls.getMethod("{VICTIM_METHOD}").invoke(vicInst);
            }} finally {{
                for (Method m : getAnnotated(vicCls, org.junit.After.class))      m.invoke(vicInst);
                for (Method m : getAnnotated(vicCls, org.junit.AfterClass.class)) m.invoke(null);
            }}
        }} catch (java.lang.reflect.InvocationTargetException e) {{
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            System.out.println("[REPRODUCED] {SAFE_KEY}: "
                + cause.getClass().getSimpleName() + ": " + cause.getMessage());
            if (cause instanceof AssertionError) throw (AssertionError) cause;
            if (cause instanceof RuntimeException) throw (RuntimeException) cause;
            throw new AssertionError("[REPRODUCED] " + cause.getMessage(), cause);
        }}
    }}
}}
""")


# ── Templates: Undertow DefaultServer runner ───────────────────────────────────
#
# NOT GENERALIZABLE — hardcoded to undertow's AnnotatedEndpointTest OD pair.
#
# Approach (mirrors old pipeline's section4b_programmatic_repro.py):
#   1. A custom Runner class extends DefaultServer, overriding computeTestMethods()
#      to sort polluter before victim.
#   2. A Suite class extends AnnotatedEndpointTest and uses @RunWith(Runner.class).
#   Both files are placed in flakyrepro/ (test source). Run with PLUS_SYNTAX.
#
# Standard surefire ordering can't guarantee polluter-first because
# BlockJUnit4ClassRunner sorts by SHA-1 hash of method name.

_UNDERTOW_RUNNER_TEMPLATE = textwrap.dedent("""\
package flakyrepro;
import io.undertow.testutils.DefaultServer;
import org.junit.runners.model.FrameworkMethod;
import org.junit.runners.model.InitializationError;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/** Generated by failure_data_collection/repro_strategies.py — deleted after run. */
public class UndertowRunner_{SAFE_KEY} extends DefaultServer {{
    private static final List<String> ORDER = Arrays.asList("{POLLUTER_METHOD}", "{VICTIM_METHOD}");

    public UndertowRunner_{SAFE_KEY}(Class<?> klass) throws InitializationError {{
        super(klass);
    }}

    @Override
    protected List<FrameworkMethod> computeTestMethods() {{
        List<FrameworkMethod> list = new ArrayList<FrameworkMethod>(super.computeTestMethods());
        Collections.sort(list, (a, b) -> {{
            int ai = ORDER.indexOf(a.getName());
            int bi = ORDER.indexOf(b.getName());
            if (ai < 0) ai = ORDER.size();
            if (bi < 0) bi = ORDER.size();
            if (ai != bi) return Integer.compare(ai, bi);
            return a.getName().compareTo(b.getName());
        }});
        return list;
    }}
}}
""")

_UNDERTOW_SUITE_TEMPLATE = textwrap.dedent("""\
package flakyrepro;
import org.junit.runner.RunWith;

/** Generated by failure_data_collection/repro_strategies.py — deleted after run. */
@RunWith(UndertowRunner_{SAFE_KEY}.class)
public class UndertowSuite_{SAFE_KEY} extends {VICTIM_CLASS} {{
}}
""")


# ── Strategy implementations ───────────────────────────────────────────────────

def run_programmatic_same_class(pair, repo_path, out_dir, env, timeout, log_path):
    """Write, compile-and-run, clean up same-class programmatic reproducer.

    Uses a two-step approach: test-compile (PHASE_B_COMPILE_TIMEOUT) then
    surefire:test (normal timeout).  This prevents a full module recompile
    from consuming the surefire timeout on large repos.
    """
    safe_key     = pair["row_key"].replace("-", "_")
    package      = pair["package"]
    victim_class = pair["victim_class"]
    victim_meth  = pair["victim_method"]
    polluter_meth= pair["polluter_method"]
    offline      = offline_flag_for(pair["repo_slug"])

    test_src_root = test_source_root_for(pair["repo_slug"])
    flakyrepro_dir = os.path.join(
        repo_path, package, test_src_root, "flakyrepro"
    ) if package not in (".", "") else os.path.join(
        repo_path, test_src_root, "flakyrepro"
    )
    os.makedirs(flakyrepro_dir, exist_ok=True)

    java_path = os.path.join(flakyrepro_dir, f"ProgrammaticReproducer_{safe_key}.java")
    src = _SAME_CLASS_TEMPLATE.format(
        SAFE_KEY=safe_key,
        VICTIM_CLASS=victim_class,
        POLLUTER_METHOD=polluter_meth,
        VICTIM_METHOD=victim_meth,
    )
    with open(java_path, "w", encoding="utf-8") as f:
        f.write(src)

    pl = f"-pl '{package}'" if package not in (".", "") else ""
    test_class = f"flakyrepro.ProgrammaticReproducer_{safe_key}"
    mvn = pair.get("mvn_cmd", "mvn")
    pre_phase = surefire_pre_phase_for(pair["repo_slug"])

    # Step 1: compile (separate timeout to handle large modules)
    compile_cmd = f"{mvn} {pl} test-compile -B {offline} {SKIP_FLAGS}"
    rc_compile, compile_output = run_cmd(compile_cmd, repo_path, env,
                                         PHASE_B_COMPILE_TIMEOUT, log_path)
    if rc_compile != 0:
        _cleanup(java_path)
        return rc_compile, compile_output

    # Step 2: run surefire:test (normal timeout; classes already compiled)
    # If a pre_phase is set (e.g. "initialize" for Sentinel), it is prepended so
    # that early-phase plugin goals (e.g. JaCoCo prepare-agent that sets @{argLine})
    # run in the same Maven session before surefire resolves its configuration.
    surefire_goals = f"{pre_phase} surefire:test" if pre_phase else "surefire:test"
    run_cmd_str = (f"{mvn} {pl} {surefire_goals} -B {offline} "
                   f"-Dtest=\"{test_class}\" "
                   f"-DforkCount=1 -DreuseForks=true "
                   f"-Dsurefire.failIfNoSpecifiedTests=false "
                   f"{SKIP_FLAGS}")
    rc, surefire_output = run_cmd(run_cmd_str, repo_path, env, timeout, log_path)
    # Append compile output so the full log is preserved
    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"\n\n--- COMPILE STEP (prepended) ---\n{compile_output}")
    except OSError:
        pass

    _cleanup(java_path)
    return rc, surefire_output


def run_programmatic_diff_class(pair, repo_path, out_dir, env, timeout, log_path):
    """Write, compile-and-run, clean up different-class programmatic reproducer.

    Uses the same two-step compile-then-test approach as run_programmatic_same_class.
    """
    safe_key      = pair["row_key"].replace("-", "_")
    package       = pair["package"]
    victim_class  = pair["victim_class"]
    victim_meth   = pair["victim_method"]
    polluter_class= pair["polluter_class"]
    polluter_meth = pair["polluter_method"]
    offline       = offline_flag_for(pair["repo_slug"])

    test_src_root = test_source_root_for(pair["repo_slug"])
    flakyrepro_dir = os.path.join(
        repo_path, package, test_src_root, "flakyrepro"
    ) if package not in (".", "") else os.path.join(
        repo_path, test_src_root, "flakyrepro"
    )
    os.makedirs(flakyrepro_dir, exist_ok=True)

    java_path = os.path.join(flakyrepro_dir, f"DiffClassReproducer_{safe_key}.java")
    src = _DIFF_CLASS_TEMPLATE.format(
        SAFE_KEY=safe_key,
        POLLUTER_CLASS=polluter_class,
        POLLUTER_METHOD=polluter_meth,
        VICTIM_CLASS=victim_class,
        VICTIM_METHOD=victim_meth,
    )
    with open(java_path, "w", encoding="utf-8") as f:
        f.write(src)

    pl = f"-pl '{package}'" if package not in (".", "") else ""
    test_class = f"flakyrepro.DiffClassReproducer_{safe_key}"
    mvn = pair.get("mvn_cmd", "mvn")
    pre_phase = surefire_pre_phase_for(pair["repo_slug"])

    # Step 1: compile (separate timeout to handle large modules)
    compile_cmd = f"{mvn} {pl} test-compile -B {offline} {SKIP_FLAGS}"
    rc_compile, compile_output = run_cmd(compile_cmd, repo_path, env,
                                         PHASE_B_COMPILE_TIMEOUT, log_path)
    if rc_compile != 0:
        _cleanup(java_path)
        return rc_compile, compile_output

    # Step 2: run surefire:test (normal timeout; classes already compiled)
    surefire_goals = f"{pre_phase} surefire:test" if pre_phase else "surefire:test"
    run_cmd_str = (f"{mvn} {pl} {surefire_goals} -B {offline} "
                   f"-Dtest=\"{test_class}\" "
                   f"-DforkCount=1 -DreuseForks=true "
                   f"-Dsurefire.failIfNoSpecifiedTests=false "
                   f"{SKIP_FLAGS}")
    rc, surefire_output = run_cmd(run_cmd_str, repo_path, env, timeout, log_path)
    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"\n\n--- COMPILE STEP (prepended) ---\n{compile_output}")
    except OSError:
        pass

    _cleanup(java_path)
    return rc, surefire_output


def run_plus_syntax(pair, repo_path, out_dir, env, timeout, log_path):
    """Run reproduction using Surefire PLUS_SYNTAX + reversealphabetical runOrder.

    No file generation needed — surefire:test runs the existing compiled classes.
    Polluter class must sort alphabetically AFTER victim class for this to work.
    """
    package       = pair["package"]
    victim_cls    = pair["victim_class"].split(".")[-1]
    victim_meth   = pair["victim_method"]
    polluter_cls  = pair["polluter_class"].split(".")[-1]
    polluter_meth = pair["polluter_method"]
    offline       = offline_flag_for(pair["repo_slug"])

    pl = f"-pl '{package}'" if package not in (".", "") else ""
    test_spec = f"{polluter_cls}#{polluter_meth},{victim_cls}#{victim_meth}"
    mvn = pair.get("mvn_cmd", "mvn")
    cmd = (f"{mvn} surefire:test {pl} -B {offline} "
           f"-Dtest=\"{test_spec}\" "
           f"-DforkCount=1 -DreuseForks=true "
           f"-Dsurefire.runOrder=reversealphabetical "
           f"-Dsurefire.failIfNoSpecifiedTests=false "
           f"{SKIP_FLAGS}")

    return run_cmd(cmd, repo_path, env, timeout, log_path)


def run_undertow(pair, repo_path, out_dir, env, timeout, log_path):
    """Write two generated files, compile+run with PLUS_SYNTAX, then clean up.

    NOT GENERALIZABLE — see module docstring.

    Mirrors old pipeline's section4b_programmatic_repro.py:
      1. UndertowRunner_{key}.java — extends DefaultServer, sorts polluter first
      2. UndertowSuite_{key}.java  — extends AnnotatedEndpointTest, @RunWith(Runner)
    Run via PLUS_SYNTAX so surefire executes polluter then victim in order.
    """
    safe_key      = pair["row_key"].replace("-", "_")
    package       = pair["package"]          # "websockets-jsr"
    victim_class  = pair["victim_class"]     # fully-qualified class name
    victim_meth   = pair["victim_method"]
    polluter_meth = pair["polluter_method"]
    mvn           = pair.get("mvn_cmd", "mvn")

    # Place generated files in flakyrepro/ under the module's test source tree
    flakyrepro_dir = os.path.join(repo_path, package, "src", "test", "java", "flakyrepro")
    os.makedirs(flakyrepro_dir, exist_ok=True)

    runner_name = f"UndertowRunner_{safe_key}"
    suite_name  = f"UndertowSuite_{safe_key}"
    runner_path = os.path.join(flakyrepro_dir, f"{runner_name}.java")
    suite_path  = os.path.join(flakyrepro_dir, f"{suite_name}.java")

    with open(runner_path, "w", encoding="utf-8") as f:
        f.write(_UNDERTOW_RUNNER_TEMPLATE.format(
            SAFE_KEY=safe_key,
            POLLUTER_METHOD=polluter_meth,
            VICTIM_METHOD=victim_meth,
        ))
    with open(suite_path, "w", encoding="utf-8") as f:
        f.write(_UNDERTOW_SUITE_TEMPLATE.format(
            SAFE_KEY=safe_key,
            VICTIM_CLASS=victim_class,
        ))

    # Two-step approach to avoid intermittent file-write timeouts in undertow:
    #   Step 1: test-compile (compiles the two flakyrepro files + main sources).
    #           Resources copy is skipped (already in target from step2).
    #           Annotation processing is disabled (-proc:none) so the JBoss
    #           logging processor doesn't try to write .i18n.properties files.
    #           Retry once if a file-write timeout occurs.
    #   Step 2: surefire:test directly — no lifecycle, no recompile.
    compile_flags = (f"-Dmaven.resources.skip=true "
                     f"-Dmaven.compiler.compilerArgument=-proc:none "
                     f"{SKIP_FLAGS}")
    compile_cmd = f"{mvn} -pl '{package}' -B -q {compile_flags} test-compile"
    compile_log  = log_path + ".compile"

    rc_c, out_c = run_cmd(compile_cmd, repo_path, env, timeout, compile_log)

    # Retry compile once if it hit a file-write timeout
    if rc_c != 0 and "Operation timed out" in out_c:
        rc_c, out_c = run_cmd(compile_cmd, repo_path, env, timeout, compile_log)

    test_spec = f"flakyrepro.{suite_name}#{polluter_meth}+{victim_meth}"
    run_surefire = (f"{mvn} surefire:test -pl '{package}' -B "
                    f"-Dsurefire.runOrder=alphabetical "
                    f"-Dtest=\"{test_spec}\" "
                    f"-DforkCount=1 -DreuseForks=true "
                    f"-Dsurefire.failIfNoSpecifiedTests=false "
                    f"-Dsurefire.useFile=false "
                    f"{SKIP_FLAGS}")

    rc, output = run_cmd(run_surefire, repo_path, env, timeout, log_path)

    # Merge compile log into main log
    compile_out = ""
    if os.path.isfile(compile_log):
        with open(compile_log) as f:
            compile_out = f.read()
        _cleanup(compile_log)
    with open(log_path, "r+") as f:
        body = f.read()
        f.seek(0)
        f.write(f"=== COMPILE (rc={rc_c}) ===\n{compile_out}\n=== SUREFIRE ===\n{body}")

    _cleanup(runner_path)
    _cleanup(suite_path)
    return rc, output


# ── Result parsing ─────────────────────────────────────────────────────────────

def parse_repro_result(output, victim_method, polluter_method):
    """
    Classify the outcome of a polluter+victim run.

    Returns one of:
      REPRODUCED
      NOT_REPRODUCED:VICTIM_PASSES_WITH_POLLUTER
      NOT_REPRODUCED:POLLUTER_ALSO_FAILED
      NOT_REPRODUCED:UNKNOWN
      BUILD_ERROR
      TESTS_NOT_FOUND
      TIMEOUT
    """
    if "TIMEOUT after" in output:
        return "TIMEOUT"

    if "No tests were run" in output or "No tests matching" in output:
        return "TESTS_NOT_FOUND"

    if not re.search(r"Tests run:", output):
        return "BUILD_ERROR"

    victim_failed = bool(
        re.search(rf"{re.escape(victim_method)}.*FAILURE", output) or
        re.search(rf"FAILURE.*{re.escape(victim_method)}", output) or
        re.search(rf"{re.escape(victim_method)}.*<<<\s*FAILURE", output) or
        "[REPRODUCED]" in output
    )
    polluter_failed = bool(
        re.search(rf"{re.escape(polluter_method)}.*FAILURE", output) or
        re.search(rf"FAILURE.*{re.escape(polluter_method)}", output)
    )

    if victim_failed and not polluter_failed:
        return "REPRODUCED"
    if not victim_failed:
        return "NOT_REPRODUCED:VICTIM_PASSES_WITH_POLLUTER"
    if polluter_failed:
        return "NOT_REPRODUCED:POLLUTER_ALSO_FAILED"
    return "NOT_REPRODUCED:UNKNOWN"


def parse_victim_alone_result(output, victim_method):
    """
    Classify the result of running the victim in isolation.

    Returns: "PASSES_ALONE" | "FAILS_ALONE" | "BUILD_ERROR" | "TESTS_NOT_FOUND"
    """
    if not re.search(r"Tests run:", output):
        return "BUILD_ERROR"
    if "No tests were run" in output:
        return "TESTS_NOT_FOUND"

    victim_failed = bool(
        re.search(rf"{re.escape(victim_method)}.*FAILURE", output) or
        re.search(rf"FAILURE.*{re.escape(victim_method)}", output) or
        re.search(rf"Tests run:.*Failures: [1-9]", output) or
        re.search(rf"Tests run:.*Errors: [1-9]", output)
    )
    return "FAILS_ALONE" if victim_failed else "PASSES_ALONE"
